"""update_payment_intent_columns

Revision ID: f1f3ff9dbb87
Revises: 240d40e8f9fe
Create Date: 2026-06-30 16:16:13.153358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1f3ff9dbb87'
down_revision: Union[str, Sequence[str], None] = '240d40e8f9fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_intents', sa.Column('provider', sa.String(length=50), nullable=False))
    op.add_column('payment_intents', sa.Column('amount', sa.String(length=20), nullable=False))
    op.add_column('payment_intents', sa.Column('status', sa.Enum('pending', 'success', 'failed', 'refunded', name='paymentstatus', native_enum=False), nullable=False))
    op.drop_column('payment_intents', 'items_snapshot')
    op.drop_column('payment_intents', 'delivery_fee')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_intents', sa.Column('delivery_fee', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('payment_intents', sa.Column('items_snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('payment_intents', 'status')
    op.drop_column('payment_intents', 'amount')
    op.drop_column('payment_intents', 'provider')
    # ### end Alembic commands ###
